### ISSUE TITLE
PSTV not working

### ISSUE THREAD

**Issue by jensma** [TheOfficialFloW/NoNpDrm#11]
Placing the plugin to ur0:/tai and load it from this tai's config file doesn't seem to work. Dumps wont update to the live area.

**Comment by jmota** [comment]
Same here, i’ll Follow the faq again shortly and ensure I implement as instructed. be right back...

**Comment by jensma** [comment]
This helped me

https://www.reddit.com/r/VitaPiracy/comments/71s4mi/pstv_usbmc_nonpdrm_anyone_got_that_working?sort=confidence
