### ISSUE TITLE
Integrated DLC

### ISSUE THREAD

**Issue by onaryc** [TheOfficialFloW/NoNpDrm#13]
Hi, 
I notice that DLC pkg can be 100k only, like the DLC was already in the main game files and unlock.

If it is the case, is there a way nonpdrm can unlock it (like full game trial)?

Thanks

**Comment by TheOfficialFloW** [comment]
no idea what you're talking about

**Comment by Makein** [comment]
Facepalm

**Comment by onaryc** [comment]
I think when a ticket was closed one can not add anything.

It is clear enough, there are several games on different plateform where the DLC data are already on the cartridge/disc/... and thes extra content is unlock with a simple file, a small one... Like trial game which contains all the needed data and is unlocked with nonpdrm.

I do not say it is the case here, but when downloading some dlc package (zeux link) i notice that there were only 100k size files (and there were a lot of them). So it seems to me that it can be an interesting thing to investigate (it is just a suggestion of course)

PS: Makin i notice your last interventions, i think you can keep it to yourself
