### ISSUE TITLE
C2-1282-1 Error encountered in-game

### ISSUE THREAD

**Issue by dallenc** [TheOfficialFloW/NoNpDrm#14]
I am currently using a PS TV with UsbMC & NoNpDRM enabled as plugins in the config file as found in the tai folder on the ur0 drive. (PS: The nonpdrm.skprx line is placed after usbmc.skprx under Kernel) Refreshing the LiveArea installs the games/apps with updates & DLCs, no issues whatsoever.

I do have problems with the following though:

(a) The above-mentioned error appears when loading certain games from the Live Area (e.g. The Last Blade 2 - perhaps a bad dump) as well as certain areas in-game for others (e.g. Yakuza Zero Companion App), which leads me to the next problem: 

(b) The NoNpDRM folder is not created and does not appear in the ux0 drive.  Does this mean that fake licenses are not being created? Am currently using version 1.1. and I do not connect to the internet when using my device. 

(c) There is a slight lag when closing a game in the LiveArea, and I have seen this happen for 2 or 3 dumps. Not sure if it is some kinda processing in the background of sorts, but it does cause a little latency especially when accessing folders in VitaShell after closing a NoNpDRM dump. The system seems to stall a little when accessing folders, and this does not happen when using games installed with Vitamin or MaiDumps.

Greatly appreciate your input with regards to my queries!
Thanks again for the wonderful work.

**Comment by dallenc** [comment]
EDIT: The nonpdrm.skprx line is placed before the usbmc.skprx under Kernel in the config.txt file within the tai folder of the ur0 drive.

Connecting to the internet and trying to update games does not create the NoNpDRM folder either.

**Comment by TheOfficialFloW** [comment]
Please explain b)...what game did you try? Game cart or digital games? And do they have a valid license?

**Comment by TheOfficialFloW** [comment]
a) bad dump, c) can't fix

**Comment by dallenc** [comment]
I've tried a mix of both digital and cartridge dumps, some of which already come with licenses for the respective DLCs and others none. The NoNpDRM does not appear regardless, neither in ur0 or ux0. Is this to be expected?

The game dumps work fine but am wondering if the lack of the folder is an issue.

**Comment by TheOfficialFloW** [comment]
Why do you expect it to create fake licenses for already dumped games?

**Comment by dallenc** [comment]
I was under the impression that I needed to copy the fake license from the folder to overwrite the already dumped game. If this is not necessary then it's all fine, my bad. Thanks again.

**Comment by TheOfficialFloW** [comment]
Wonderful logic. You want to dump the fake license of a game that uses a fake license already in order to replace its fake license with the new fake license.

**Comment by Makein** [comment]
xDDD
