### ISSUE TITLE
Compatibility with SD2VITA as external storage

### ISSUE THREAD

**Issue by masoudr** [TheOfficialFloW/NoNpDrm#15]
Hi,
I'm using SD2VITA as my external storage (uma0), I'm trying to copy some apps to this directory but when I refresh the live area it can't find any of my apps. But these apps work fine with vita memory as ux0. How can I solve this, is there any way to use NoNpDrm with sd2vita as external memory?
Thanks

**Comment by Makein** [comment]
This mot issue, you need other plugin for it. 
SD2VITA as external storage (**uma0**) would not find any games.
Look for app manager
