### ISSUE TITLE
NONPDRM NOT WORKING

### ISSUE THREAD

**Issue by Vegeta780** [TheOfficialFloW/NoNpDrm#16]
Hello guys greetings And thanks for wonderful app. 
i downloaded pkg game and extract with pkg_dec 
i put game folder into ux0:app 
`# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from molecularShell for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/nonpdrm.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx

*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*KERNEL
ur0:vitacheat/vitacheat.skprx
`
my file nonpdrm.skprx in ur0:tai 
above is my setting
i reboot psvita and load vitashell when i click on refresh livearea
refresh0 items 
x ok

I try many  website topic  to solve this problem but nothing happen 
is it beacuse i edit app.db ? or i delete the tai folder in ux0 
Thanks in advance

**Comment by Vegeta780** [comment]
why close

**Comment by TheOfficialFloW** [comment]
Because stupid

**Comment by Vegeta780** [comment]
oops i don't see where am going my bad

**Comment by Vegeta780** [comment]
rushing things sorry
well any suggestion on my issue

**Comment by MarioMasta64** [comment]
lol

**Comment by TheRadziu** [comment]
It is not an issue with nonpdrm, so flow was right closing it. 
You better ask on reddit or certain discord servers, because github is not a right place to ask such a question.

**Comment by nebu187** [comment]
be sure to remove the cartridge from the slot & the bubble of the game before refreshing the live area.
