### ISSUE TITLE
[Bug ?] Starting Ys VIII crashes whole PS Vita O.o

### ISSUE THREAD

**Issue by Gnarmagon** [TheOfficialFloW/NoNpDrm#18]
I don't know if it will be anyhow usefull but is it intended that the PSVita displays on the first startup a Error Code (C1-6703-6 and I am not using a Testkit) and the PSVita always shutsdown and reboots when the Game is started.
It's the EU Version extracted with pkg2zip.

Maybe it's somehow intresting, feel free to close this Issue if you don't care about it lol

**Comment by TheRadziu** [comment]
The first error is because EU release is 3.61+. 
I'm not sure if vita crashes with all 3.61+ titles or not.

**Comment by MarioMasta64** [comment]
i havr my vita crash whenever i try to play gal gunv double peace.

**Comment by Makein** [comment]
It's your problem, not this downloader

**Comment by Gnarmagon** [comment]
@Makein What are you talking about ? What downloader ?
