### ISSUE TITLE
Having trouble getting this to work with usbmc

### ISSUE THREAD

**Issue by AyanamiRei1** [TheOfficialFloW/NoNpDrm#24]
Alright before updating to Enso 3.65 this all worked but now it doesn't refresh any of my previously working nonpdrm titles I haven't got a clue what I'm doing wrong the plugin is in ur0 and ux0 because I thought I would try ux0 because ur0 isn't working at all but neither is ux0. So I really don't know what's wrong.

**Comment by rellikami** [comment]
Confirming this on my pstv have the same issue.

**Comment by AyanamiRei1** [comment]
Yep I downloaded usbmc from the release tab and same goes for nonpmdrm

**Comment by AyanamiRei1** [comment]
Yep using the most recent versions of both plugins nonpmdrm fails to load

**Comment by 9BitStrider** [comment]
I can confirm that the plug-in does not function with usbmc. Using a 3G Vita with SphereSolid's SD adaptor and a 128gb card.

config.txt is as follows:

*KERNEL
ur0:tai/nonpdrm.skprx
ur0:tai/usbmc.skprx

Tried unlinking the SD card, rebuilding the database, and formatting the SD card for a fresh start. No changes. Games were tested from PKGj and VitaPiracy's "Premium" Crunchyroll dump.

**Comment by Pixelise** [comment]
I can also confirm that usbmc and nonpdrm don't like eachother very much

**Comment by rellikami** [comment]
figured it out check the internal memory card (mount ima0 in vitashell) for a config.txt in the tai folder delete it or change the name then check your ux0 folder as well and delete that one too if present.
reboot and everything should work all of my nonpdrm games work now, and pkgi can install them again.
Make certain the only config file you have is in the tai folder in ur0.
