### ISSUE TITLE
Refreshing Livearea and 0 games added when not transferring using Windows

### ISSUE THREAD

**Issue by gut5** [TheOfficialFloW/NoNpDrm#25]
I'm using FTP (Ubuntu Linux 16.04) to transfer games and getting this problem where the game is present on the memory card but refreshing it in Vitashell doesn't "see" the games. The folders are correct.

**Comment by TheOfficialFloW** [comment]
how is this an issue of NoNpDrm? Your transfer has been corrupted then.

**Comment by gut5** [comment]
I wasn't sure what component was causing this, but it's happening all the time, with various games, the transfer goes through successfully on Filezilla with no issues, and I'm not the only person who has had this, I've seen several people report this problem though I don't think anyone has opened an issue here. 
Sorry if this is the wrong component to open this issue under, could you help me figure out what's going on here? I've tried it transferring multiple times with the same game, and always have the same problem. The game itself has been reported to work fine for other people (who are using Windows to transfer over USB).
