### ISSUE TITLE
C1-6703-6

### ISSUE THREAD

**Issue by barbabarros** [TheOfficialFloW/NoNpDrm#28]
Im using 3.65 enso with nonpdrm, download enabler and nopsmdrm plugins...
Secret Of Mana gives C1-6703-6 error. If i try to start the game twice, the vita reboots.
Not a dev unit. My vita is a 3g model. Thank u.

**Comment by mathieulh** [comment]
Secret of mana is a 3.67 game.

**Comment by barbabarros** [comment]
Yeah... i saw that too late. Already bought but im on 3.65 enso now. Thanks for your time!
