### ISSUE TITLE
gamecard content copies over ux0:/app/TITLE_ID won't work

### ISSUE THREAD

**Issue by thaikhoa** [TheOfficialFloW/NoNpDrm#3]
Hi,

What I did

copy the gamecard content from gro0:app/TITLE_ID to ux0:/app/TITLE_ID
rename 6488b73b912a753a492e2714e9b38bc7.rif (once dump when playing it on the first place) to work.bin and copy to ux0:/app/TITLE_ID/sce_sys/package/

Play the game and it won't run, error code C0-11136-2 You must download the application again from Download List in PS Store.

Thanks for the amazing plugin.

**Comment by thaikhoa** [comment]
Got it to work when copying the fake license to ux0:/license

Sorry for that.

**Comment by TheOfficialFloW** [comment]
That's because you did not refresh livearea

**Comment by masterrite** [comment]
Some of the game cards doesn't have a work.bin at all, like YS viii Asian version.
