### ISSUE TITLE
How do i install NoNpDrm when using h-encore, if rebooting disables h-encore?

### ISSUE THREAD

**Issue by LazyBunny** [TheOfficialFloW/NoNpDrm#35]
Like the title. I tried installing this, but i don't think it's working. Since it says to reboot the device, but since h-encore is a soft hack, it doesn't persist through the reboot. So i'm wondering what i'm doing wrong.

**Comment by TheOfficialFloW** [comment]
h-encore loads plugins by the time you exit the bootstrap menu lol
