### ISSUE TITLE
How do I bypass the system activation?

### ISSUE THREAD

**Issue by Conan179** [TheOfficialFloW/NoNpDrm#4]
(Wie umgehe ich die systemaktivierung?)
Hello. I have a small problem and if I want to start my ps + games, announces my vita (with enso) that I must activate them to play the games. What can I do?

I use google translate, i speak German.
(Hallo. Ich hab da ein kleines problem und zwar wenn ich meine ps+ spiele starten möchte, meldet meine vita (mit enso) das ich sie Aktivieren muss um die spiele zu spielen. Was kann ich machen?)

**Comment by TheOfficialFloW** [comment]
You can't

**Comment by mathieulh** [comment]
Have you dumped the license for these games? Is your system still activated? (Is act.dat present in tm0:npdrm/act.dat ?)

You can only run games your device is activated (has licenses for) or for which you have a fake license copied as TITLE_ID/sce_sys/package/work.bin

**Comment by Conan179** [comment]
no, this vita dosnt have a activation. it was a fw 3.12 for epsp and updatet for henkakau (After blocking the activation by sony).
I have a second vita, which has an activation, but a hardware defect. I do not want to use them anymore.

**Comment by mathieulh** [comment]
You can't run games you do not have a valid license or fake license for. Applications running using npdrm require a key to run (which is part of the license file), NoNpDrm cannot "guess" the proper key for each game through some magical mean.

Please read the readme before opening issues.

**Comment by Conan179** [comment]
you wrote, real or fake license ok, where I get the fake license?

**Comment by mathieulh** [comment]
You can only get it by running your games on an activated console with the NoNpDrm module loaded.

If you have no way of running your games in the first place you can't get it.

PLEASE READ THE README BEFORE ASKING QUESTIONS. Thank you for your understanding.

**Comment by Conan179** [comment]
ok i delete the this from my vita. thanks.

**Comment by TheOfficialFloW** [comment]
The only way you can get it is by friends who have got the same game and region

**Comment by Conan179** [comment]
@TheOfficialFloW How do you explain the sentence: "Using purchased applications on deactivated devices." But you can not circumvent the activation. My PS + games do not start, because my vita is not activat.
