### ISSUE TITLE
Bug in fake license generation for shared DLCs

### ISSUE THREAD

**Issue by Yoti** [TheOfficialFloW/NoNpDrm#44]
I have a Digimon from game card (PCSG01126) as NoNpDrm dump and DLCs from the PS Store (PCSG01119). According to the PARAM.SFO this game using "shared" DLCs with regular edition (PCSG01119). But when I run the game NoNpDrm doesn't produce fake licences for the DLCs (as result I have no ux0:nonpdrm/ at all).

System: PCH-2006 + 4 GB $ONY card @ 3.68 FW w/ latest NoNpDrm release.
PARAM.SFO: https://imgur.com/rACtXIk
Game: https://www.reddit.com/r/VitaPiracy/comments/a13c6a/pcsg01126_digimon_story_cyber_sleuth_hackers/

**Comment by eadmaster** [comment]
maybe i have a similar issue here with Wipeout 2048 + DLCs (US) (PCSA00015).

some licenses are generated in `ux0:license/.../PCSA00015`, but there is none in `ux0:nonpdrm/` and the game is not loading the DLCs...

**Comment by fumu-no-kagomeko** [comment]
Sorry for the notificaiton spam.

Could you try out [this build](https://github.com/TheOfficialFloW/NoNpDrm/files/2849094/nonpdrm.skprx.zip) and see if it works?

**Comment by Yoti** [comment]
> Sorry for the notificaiton spam.
> 
> Could you try out [this build](https://github.com/TheOfficialFloW/NoNpDrm/files/2849094/nonpdrm.skprx.zip) and see if it works?

C0-9250-6 on all NND games.

**Comment by fumu-no-kagomeko** [comment]
> C0-9250-6 on all NND games.

Everything works fine here, though. :thinking:
According to the README, that error is when NoNpDrm is not loaded.

Just made a modification to write the extracted `INSTALL_DIR_ADDCONT` value to a file. The file had expected content and all games run just fine.

What did you do? :thinking: 

SHA-256 of the attached plugin is `7668d37bd79fe2c993a33cc7646422a8297b0951c197252b9e5593932bf4760b` in any case.

**Comment by Yoti** [comment]
> SHA-256 of the attached plugin is `7668d37bd79fe2c993a33cc7646422a8297b0951c197252b9e5593932bf4760b` in any case.

Just tried again, all works fine.
