### ISSUE TITLE
not work on pstv

### ISSUE THREAD

**Issue by nictse2013** [TheOfficialFloW/NoNpDrm#45]
with Henkaku Enso via USB memory
i put the plugin in ur0:tai/
config like 

*KERNEL
ur0:tai/nonpdrm.skprx

but still not work....

i googled, many friends have this problem

**Comment by snintendog** [comment]
seconding i have my Vita tv mounting a USB as ux0: no dumps of the license or genning of folders even after manually creating the folder no luck
