### ISSUE TITLE
Legit updates and DLC won't install even on legit games on VitaTV

### ISSUE THREAD

**Issue by NeoTechni** [TheOfficialFloW/NoNpDrm#47]
Anytime I try to install DLC/updates, it skips the install process and just opens the game.

Not a huge concern since I own all the games/content on my system and can disable the plugin without any loss. But I figured you'd want to know about it.

**Comment by NeoTechni** [comment]
Oh, that's why I have it installed... I need it for ref00d... I was wondering why I had it if I didn't use any backups/piracy.

**Comment by Yoti** [comment]
Remove antiblacklist.

**Comment by NeoTechni** [comment]
But I need that, since it's a VitaTV. The thing is practically useless without it.

**Comment by Yoti** [comment]
This is not a NoNpDrm issue. You must
1) Remove antiblacklist
2) Install updates and/or DLCs
3) Install antiblacklist again
every time you want to do second step.
