### ISSUE TITLE
Live Area

### ISSUE THREAD

**Issue by Asentum** [TheOfficialFloW/NoNpDrm#48]
Version of firmware: [3.60]
Version of PKGj: [v0.51]
Version of VitaShell [1.98]

I left a similar post on the PKGj board because I'm not sure if this is an issue with an incorrectly installed freeshop or NoNpDrm. Any help is appreciated!

Some PS Vita games download correctly, and others do not. I've successfully installed games like V3, Persona 4, and Hotline Miami. However, when I try to install games like Trails of Cold Steel, and Ys: Memories of Celceta I get the following error code. "Could Not Download. (C0-11303-8)"

I'm unsure of how to reproduce the issue but I'll give as many details as I can. I am using SD2VITA, with 256 gigs of space (176.53 is still free) and have NoNpDrm, and reFOOD both installed. I'm currently spoofing 3.68. NoNpDrm must be installed correctly becasue I've managed to install various other titles. I should also mention I've tried refreshing the data base, and that my NoNpDrm plugin is located in my ur0:tai folder along with the config file. I had tai folders in both Uamo, and Uxo, and both have been deleted. 

However, when I try to install games manually through the NPS browser, I refresh the live area in vitashell, and none of my games appear; though they appear to be installed in the PKGj store. What's interesting is that if I go back and look inside those game folders after transfering them into my apps folder is that none of the files are there except for the file folder containing the game ID. (nothing is in the folder at all.)

I'm not sure what I've done wrong between the NoNpDrm, and PKGj but any help is appreciated!

**Comment by TheOfficialFloW** [comment]
Not an issue of VitaShell.
