### ISSUE TITLE
Support for 3.71?

### ISSUE THREAD

**Issue by windsurfer1122** [TheOfficialFloW/NoNpDrm#50]
Will there be an update for 3.69/3.70/3.71?
Or does the current version already work correctly on these firmwares?

**Comment by Masters110** [comment]
No 3.71 has blocked it

**Comment by flying-night-slasher** [comment]
Is there an alternate DRM bypass plugin for 3.73?

**Comment by Masamune3210** [comment]
Just downgrade to 3.60
