### ISSUE TITLE
Copy Fake license to Digital Game - Gravity Rush after launch got an error C1-11843-7

### ISSUE THREAD

**Issue by hsuanpai** [TheOfficialFloW/NoNpDrm#6]
Hi ,

1.Copy fake license 6488b73b912a753a492e2714e9b38bc7.rif to ux0:/license/app/PCSD00003
There are two files in folder of ux0:/license/app/PCSD00003 as list below:
  6488b73b912a753a492e2714e9b38bc7.rif
  feb50812027c26f22bda054fd5810779.rif (if deleted this file will got the C1-11843-7.)
  Rename from feb50812027c26f22bda054fd5810779.rif to 6488b73b912a753a492e2714e9b38bc7.rif 
  (Will get similar error "Need to activation the device" )
2.Copy fake license of 6488b73b912a753a492e2714e9b38bc7.rif as work.bin into ux0:/app/PCSD00003/sce_sys/package .
3.Press △ in the home section of VitaShell and choose Refresh livearea.
4.Launch Gravity Rush and got an error C1-11843-7(if feb50812027c26f22bda054fd5810779.rif not exist.) or Need Active (if rename original .rif to 6488b73b912a753a492e2714e9b38bc7.rif).

**Comment by TheOfficialFloW** [comment]
Delete ux0:license/PCSD00003 folder and try refresh again.

**Comment by hsuanpai** [comment]
After Deleted ux0:license/PCSD00003 folder and refresh got new error C0-11136-2.

**Comment by TheOfficialFloW** [comment]
Can you upload the fake license?

**Comment by hsuanpai** [comment]
[6488b73b912a753a492e2714e9b38bc7.zip](https://github.com/TheOfficialFloW/NoNpDrm/files/1307760/6488b73b912a753a492e2714e9b38bc7.zip)

**Comment by TheOfficialFloW** [comment]
You are using a fake license of a different game, how can that not fail lol.

**Comment by hsuanpai** [comment]
So, I can't use another games generated fake license to instead that I want to launch the game?
But the game download from PSN any way to play ?

**Comment by mathieulh** [comment]
No, you cannot, fake licenses contain a PER TITLE key, those will only work for the title id they are tied to.

**Comment by KaschWarckaterus** [comment]
It may be a corner case, but I also got C1-11843-6 after migrating from mai-dumps of my games to nonpdrm-dumps because of the missing save encryption.
It would be helpful if it was added to the readme (imo).
Also sorry TheOfficialFloW for sending too many messages regarding the Adrenaline act.dat problem.
