### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by chronoss09** [TheOfficialFloW/NoNpDrm#8]
I have a Ratchet & Clank Trilogy game card but the plugin can't create a fake plugin. can u solve that ?

**Comment by mathieulh** [comment]
You mean you actually have the card and when you run the game the license isn't created in ux0:/nonpdrm/license/app/TITLEID ? You do have the nonpdrm.skprx module loaded right?

**Comment by chronoss09** [comment]
yes, i have a plugin installed
