### ISSUE TITLE
Forced memory card format bug

### ISSUE THREAD

**Issue by AlternativeZero** [TheOfficialFloW/NoNpDrm#9]
I really don't know how to explain this one since there could be any number of causes but this only occurred after copying over several NoNpDrm backups and following provided instructions on how to install them but it could honestly be a whole number of things.

Through ordinary usage I've encountered the error C0-11277-8 when trying to delete a game from the livearea with error vode 0x8001000D when trying to delete the folder in VitaShell although the contents can be deleted but the folder itself remains.

When trying to install a vpk VitaShell will give the error 0x80AF5025 and when using the refresh the livearea option it shows the result as 0.

The only known fix for this is by formatting the memory card and then reinstalling everything from scratch. If possible could you take a look at this issue to see if perhaps something in the process is causing such an issue?

**Comment by TheOfficialFloW** [comment]
Not an issue with NoNpDrm.

**Comment by AlternativeZero** [comment]
Sorry but I've done that but the error still persists.

**Comment by TheOfficialFloW** [comment]
Sorry it is still not an issue of the plugin?

**Comment by AlternativeZero** [comment]
I'm not sure, I've only received this error once I started using NoNpDrm but it could be something else during the process of copying files to memory card then selecting refreshing the livearea.

Sorry if this isn't as helpful but I've seen some people getting this issue.
